### PR TITLE
issue-4: added check that season has percentOfEpisodes statistic

### PR DESCRIPTION
**Pull request by alex-joyce**
Fix for issue 4, done in the same way as the previous check on line 63 that the show has seasons

### CODE REVIEW

**Comment by Cosine5000** [comment]
Seeing same issue:
Traceback (most recent call last): File "/usr/src/app/mdblistrr/cron.py", line 65, in post_sonarr_payload if season['statistics']['percentOfEpisodes'] == 100: KeyError: 'statistics'

**Comment by alex-joyce** [comment]
> Seeing same issue:
> 
> Traceback (most recent call last): File "/usr/src/app/mdblistrr/cron.py", line 65, in post_sonarr_payload if season['statistics']['percentOfEpisodes'] == 100: KeyError: 'statistics' 

Did you clone the main branch?

**Comment by Cosine5000** [comment]
I have not changed anything, problem started on Feb 26.

**Comment by linaspurinis** [comment]
You can try v2 beta version with multiple Radarr and Sonarr instances support:

build and from the command line:
```
git clone --branch v2-beta git@github.com:linaspurinis/mdblistarr.git
docker build -t mdblistarr .
docker run -e PORT=5353 -p 5353:5353 mdblistarr
```

or docker-compose:
```
version: '3'
services:
  mdblistarr:
    container_name: mdblistarr
    image: linaspurinis/mdblistarr:v2-beta
    environment:
      - PORT=5353
    volumes:
      - db:/usr/src/db/
    ports:
      - '5353:5353'
volumes:
  db:
```

**Comment by Cosine5000** [comment]
I'm just running it from the unRAID docker. Since the 26th the problem has
not recurred.

**Comment by alex-joyce** [comment]
> You can try v2 beta version with multiple Radarr and Sonarr instances support:
> 
> build and run from the command line:
> 
> ```
> git clone --branch v2-beta git@github.com:linaspurinis/mdblistarr.git
> docker build -t mdblistarr .
> docker run -e PORT=5353 -p 5353:5353 mdblistarr
> ```
> 
> or docker-compose:
> 
> ```
> version: '3'
> services:
>   mdblistarr:
>     container_name: mdblistarr
>     image: linaspurinis/mdblistarr:v2-beta
>     environment:
>       - PORT=5353
>     volumes:
>       - db:/usr/src/db/
>     ports:
>       - '5353:5353'
> volumes:
>   db:
> ```

I've just switched my docker compose over to v2-beta and am having the same issue as @Cosine5000 

The issue is my line 65 in cron.py 

`if season.get('statistics').get('percentOfEpisodes'):`

Errors when season.get('statistics') is NoneType as it trys to do another .get()

PR raised with a fix which separates this out into two ifs which will skip trying the second .get() if statistics isn't present in the dict:

```
                        if season.get('statistics'):
                            if season.get('statistics').get('percentOfEpisodes'):
```

**Comment by linaspurinis** [comment]
Fixed. Please refresh, thank you.

**Pull request merged**
